/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ClientImpl */

#ifndef _Included_ClientImpl
#define _Included_ClientImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef ClientImpl_serialVersionUID
#define ClientImpl_serialVersionUID -3215090123894869218LL
#undef ClientImpl_serialVersionUID
#define ClientImpl_serialVersionUID -4100238210092549637LL
#undef ClientImpl_serialVersionUID
#define ClientImpl_serialVersionUID 4974527148936298033LL
/*
 * Class:     ClientImpl
 * Method:    CGetLocalTime
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ClientImpl_CGetLocalTime
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ClientImpl
 * Method:    CGetLocalOS
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_ClientImpl_CGetLocalOS
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
